name: dev

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    - cron: "30 18 * * *" # run at 00:00 AM IST

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11

      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org"

      - name: Build - AAS
        working-directory: ./csw-aas-js
        run: |
          npm ci
          npm run lint 
          npm run build

      - name: Test - AAS
        working-directory: ./csw-aas-js
        run: npm test

      - name: Build - Config App
        working-directory: ./csw-aas-js-examples/config-app
        run: |
          npm ci
          npm run build

      - name: Build - Example App
        working-directory: ./csw-aas-js-examples/example-app
        run: |
          npm ci
          npm run build

      - name: Selenium Test
        run: sbt clean test

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-dev
